[package]
name = "prodio"
version = "0.1.0"
authors = ["YutaNagaoka <shirasu.okatin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
